export const products = [
    {
        id:1,
        title:"100% Pure Peach Juice",
        desc:"This is a description text.",
        price:550,
        colors:["white"],
        sizes:["xl"],
        categories:["fruits","milkandcreams"],
        image:"/Assests/ProductItems/item1.jpg",
        createdAt:"1/21/2024",
    },
    {
        id:2,
        title:"Item 2",
        desc:"This is a description text.",
        price:180,
        colors:["black"],
        sizes:["sm","m","l"],
        categories:["women cloth","men cloth"],
        image:"/Assests/ProductItems/item2.jpg",
        createdAt:"1/21/2024",
    },
    {
        id:3,
        title:"Men White And Blue T-Shirt",
        desc:"This is a description text.",
        price:1050,
        colors:["white","blue"],
        sizes:["xl","l"],
        categories:["men cloth"],
        image:"/Assests/ProductItems/item3.jpg",
        createdAt:"1/21/2024",
    },
    {
        id:4,
        title:"Trousers",
        desc:"This is a description text.",
        price:280,
        colors:["white"],
        sizes:["s"],
        categories:["women cloth","men cloth"],
        image:"/Assests/ProductItems/item4.jpeg",
        createdAt:"1/21/2024",
    },
    {
        id:5,
        title:"Shirt",
        desc:"This is a description text.",
        price:90,
        colors:["red","pink","brown"],
        sizes:["s","m","xl"],
        categories:["women cloth"],
        image:"/Assests/ProductItems/item5.jpeg",
        createdAt:"1/21/2024",
    },
]