export const products = [
    {
        id:1,
        title:"100% Pure Peach Juice",
        desc:"This is a description text.",
        price:550,
        colors:["white"],
        sizes:["xl"],
        categories:["milkandcreams","all"],
        image:"/Assests/ProductItems/item1.jpg",
        createdAt:"1/21/2024",
    },
    {
        id:2,
        title:"100% Organic Orange",
        desc:"This is a description text.",
        price:180,
        colors:["black"],
        sizes:["sm","m","l"],
        categories:["all","fruits"],
        image:"/Assests/ProductItems/item2.jpg",
        createdAt:"1/21/2024",
    },
    {
        id:3,
        title:"100% Organic StrawBerry",
        desc:"This is a description text.",
        price:1050,
        colors:["all"],
        sizes:["xl","l"],
        categories:["all","fruits"],
        image:"/Assests/ProductItems/item3.jpg",
        createdAt:"1/21/2024",
    },
    {
        id:4,
        title:"12 Peices , A Dozen Of Australian Banana",
        desc:"The Australian banana is characterized by its elongated, slightly curved shape. The peel is thin and smooth, transitioning from green to yellow as it ripens. The fruit typically measures a few inches in length and has a distinctive gentle curve.",
        price:675,
        colors:["all"],
        sizes:["s"],
        categories:["all","fruits"],
        image:"/Assests/ProductItems/item4.jpeg",
        createdAt:"1/23/2024",
    },
    {
        id:5,
        title:"Pineapple",
        desc:"Discover the epitome of tropical indulgence with our farm-fresh, premium pineapples. These succulent fruits are meticulously selected at their peak ripeness, ensuring a burst of natural sweetness and flavor in every bite.",
        price:90,
        colors:["red","pink","brown"],
        sizes:["s","m","xl"],
        categories:["all","fruits"],
        image:"/Assests/ProductItems/item5.jpeg",
        createdAt:"1/21/2024",
    },
]